print("Starting")

import board

from kmk.kmk_keyboard import KMKKeyboard
from kmk.keys import KC
from kmk.scanners import DiodeOrientation

keyboard = KMKKeyboard()
# Cleaner key names
_______ = KC.TRNS
XXXXXXX = KC.NO

keyboard.row_pins = (board.GP0, board.GP1, board.GP2, board.GP3, board.GP4, board.GP5, board.GP6, board.GP7, )
keyboard.col_pins = (board.GP8, board.GP9, board.GP10, board.GP11, board.GP12, board.GP13, board.GP14, board.GP15, board.GP16, board.GP17, board.GP18, board.GP19, board.GP20, board.GP21, board.GP22, board.GP26, )
keyboard.diode_orientation = DiodeOrientation.COL2ROW


keyboard.keymap = [[
    KC.PRINT_SCREEN,    
    KC.RIGHT,
    _______,
    KC.RIGHT_ALT,
    _______,
    _______,
    KC.F12,
    KC.INSERT,
    KC.5,
    KC.R,
    KC.4,
    KC.6
    KC.V,
    KC.F,
    _______,
    KC.SPACE,
    KC.LEFT,
    KC.RIGHT_CONTROL,
    _______,
    _______,
    _______,
    _______,
    KC.SCROLL_LOCK,
    KC.G,
    KC.F5,
    KC.PGUP,
    _______,
    _______,
    _______,
    _______,
    KC.LCTRL,
    KC.ENT,
    KC.DOWN,
    _______,
    _______,
    KC.RIGHT_SHIFT,
    _______,
    KC.F11,
    KC.DELETE,
    KC.F1,
    KC.CAPS_LOCK,
    KC.2,
    KC.W,
    KC.X,
    _______,
    KC.T,
    KC.S,
    _______,
    KC.BACKSPACE,
    _______,
    _______,
    _______,
    KC.RIGHT_SUPER,
    KC.F10,
    KC.F9,
    KC.F6,
    KC.END,
    KC.HOME,
    _______,
    _______,
    KC.LEFT_CONTROL,
    _______,
    _______,
    KC.O,
    KC.UP,
    KC.DOT,
    KC.L,
    _______,
    _______,
    KC.9,
    KC.F8,
    KC.F4,
    KC.F7,
    KC.PGDOWN,
    _______,
    KC.LEFT_ALT,
    _______,
    _______,
    _______,
    KC.I,
    _______,
    KC.COMMA,
    KC.K,
    KC.BACKSLASH,
    KC.RBRACKET,
    KC.8,
    KC.EQUAL,
    KC.GRAVE,
    KC.Q,
    KC.1,
    KC.TAB,
    KC.Z,
    KC.A,
    _______,
    KC.ESCAPE,
    KC.P,
    KC.SLASH,
    _______,
    KC.QUOTE,
    KC.SEMICOLON,
    KC.LBRACKET,
    KC.0,
    KC.MINUS,
    _______,
    KC.SPACE,
    KC.FN,
    KC.LSHIFT,
    _______,
    _______,
    _______,
    _______,
    KC.U,
    KC.N,
    KC.m,
    KC.J,
    KC.H,
    KC.Y,
    KC.7,
    _______,
    KC.F2,
    KC.E,
    KC.3,
    KC.F3,
    KC.C,
    KC.D,
    _______,
    KC.B ]]
if __name__ == '__main__':
    keyboard.go()